src/com/ssm/bean/SysUser.java
package com.ssm.bean;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import tk.mybatis.mapper.annotation.NameStyle;
import tk.mybatis.mapper.code.Style;

@Entity
@Table(name = "t_sysuser")
@NameStyle(Style.normal)
public class SysUser {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer	id;

	@Column(name = "uname", nullable = false, unique = true, length = 20)
	private String	uname;
	@Column(name = "userName", nullable = false, length = 20)
	private String	userName;
	@Column(name = "userPassword", nullable = false, length = 250)
	private String	userPassword;
	private String	userGender;
	private String	userPhone;
	private String	userEmail;
	private String	userAddress;
	private String	userBirth;

	@Transient
	public String getRole() {
		return "管理员";
	}

	public SysUser() {
	}

	public Integer getId() {
		return id;
	}

	public String getUname() {
		return uname;
	}

	public String getUserName() {
		return userName;
	}

	public String getUserPassword() {
		return userPassword;
	}

	public String getUserGender() {
		return userGender;
	}

	public String getUserPhone() {
		return userPhone;
	}

	public String getUserEmail() {
		return userEmail;
	}

	public String getUserAddress() {
		return userAddress;
	}

	public String getUserBirth() {
		return userBirth;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public void setUserGender(String userGender) {
		this.userGender = userGender;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public void setUserBirth(String userBirth) {
		this.userBirth = userBirth;
	}

}

src/com/ssm/bean/Teacher.java
package com.ssm.bean;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.ssm.util.FD;

import tk.mybatis.mapper.annotation.NameStyle;
import tk.mybatis.mapper.code.Style;

@Entity
@Table(name = "t_teacher")
@NameStyle(Style.normal)
public class Teacher {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer	id;
	@FD("工号")
	@Column(name = "uname", nullable = false, unique = true, length = 20)
	private String	uname;
	@FD("姓名")
	@Column(name = "userName", nullable = false, length = 20)
	private String	userName;
	@Column(name = "userPassword", nullable = false, length = 250)
	private String	userPassword;
	private String	userGender;
	private String	userPhone;
	private String	userEmail;
	private String	userAddress;
	private String	userBirth;

	private String	photo;

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Transient
	public String getFname() {
		return userName + "(" + uname + ")";
	}

	@Transient
	public String getRole() {
		return "教师";
	}

	public Teacher() {
	}

	public Integer getId() {
		return id;
	}

	public String getUname() {
		return uname;
	}

	public String getUserName() {
		return userName;
	}

	public String getUserPassword() {
		return userPassword;
	}

	public String getUserGender() {
		return userGender;
	}

	public String getUserPhone() {
		return userPhone;
	}

	public String getUserEmail() {
		return userEmail;
	}

	public String getUserAddress() {
		return userAddress;
	}

	public String getUserBirth() {
		return userBirth;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public void setUserGender(String userGender) {
		this.userGender = userGender;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public void setUserBirth(String userBirth) {
		this.userBirth = userBirth;
	}

}

WebRoot/jsp/addPaper.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../common/head.jsp"%>
<%@ page import="com.ssm.util.Constant" %> 
<div class="bjui-pageContent">
	<form action="${ctx}/sys/add${actionclass}.do" id="j_custom_form" data-toggle="ajaxform">
		<div class="bjui-row col-3">
			<label class="row-label">所属科目</label>
			<div class="row-input">
				<select name="courseId" id="Paper_course" data-rule="required">
					<c:forEach items="${list }" var="item">
						<option value="${item.id }">${item.name }</option>
					</c:forEach>
				</select>
			</div>
			<br />

			<label class="row-label">试卷名称</label>
			<div class="row-input">
				<input type="text" name="name" id="Paper_name" value="${modifybean.name}" data-rule="required">
			</div>
			<br />

			<label class="row-label">考试时长(分钟)</label>
			<div class="row-input">
				<input type="text" name="examTime" id="Paper_examTime" value="${modifybean.examTime}" data-rule="required;digits">
			</div>
			<br />
			<label class="row-label">单选题数量</label>
			<div class="row-input">
				<input type="text" name="danxuan" id="danxuan" value="" data-rule="required;digits">
			</div>
			<label class="row-label">单选题分值</label>
			<div class="row-input">
				<input type="text" name="danxuanfen" id="danxuanfen" value="<%=Constant.danxuan %>" data-rule="required;digits">
			</div>
			<br />
			<label class="row-label">多选题数量</label>
			<div class="row-input">
				<input type="text" name="duoxuan" id="duoxuan" value="" data-rule="required;digits">
			</div>
			<label class="row-label">多选题分值</label>
			<div class="row-input">
				<input type="text" name="duoxuanfen" id="duoxuanfen" value="<%=Constant.duoxuan %>" data-rule="required;digits">
			</div>
			<br />
			<label class="row-label">判断题数量</label>
			<div class="row-input">
				<input type="text" name="panduan" id="panduan" value="" data-rule="required;digits">
			</div>
			<label class="row-label">判断题分值</label>
			<div class="row-input">
				<input type="text" name="panduanfen" id="panduanfen" value="<%=Constant.panduan %>" data-rule="required;digits">
			</div>
			<br />
			<label class="row-label">填空题数量</label>
			<div class="row-input">
				<input type="text" name="tiankong" id="tiankong" value="" data-rule="required;digits">
			</div>
			<label class="row-label">填空题分值</label>
			<div class="row-input">
				<input type="text" name="tiankongfen" id="tiankongfen" value="<%=Constant.tiankong %>" data-rule="required;digits">
			</div>
			<br />
			<label class="row-label">简答题数量</label>
			<div class="row-input">
				<input type="text" name="jianda" id="jianda" value="" data-rule="required;digits">
			</div>
			<label class="row-label">简答题分值</label>
			<div class="row-input">
				<input type="text" name="jiandafen" id="jiandafen" value="<%=Constant.jianda %>" data-rule="required;digits">
			</div>
			<br />

			<label class="row-label">有效</label>
			<div class="row-input">
				<select name="youxiao">
					<option value="是">是</option>
					<option value="否">否</option>
				</select>
			</div>
			<br />


		</div>
	</form>
</div>
<div class="bjui-pageFooter">
	<ul>
		<li>
			<button type="button" class="btn-close" data-icon="close">取消</button>
		</li>
		<li>
			<button type="submit" class="btn-default" data-icon="save">保存</button>
		</li>
	</ul>
</div>

WebRoot/jsp/anlExamScore.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../common/head.jsp"%>
<div class="bjui-pageHeader">
	<form data-toggle="ajaxsearch" action="${ctx}/sys/anlExamScore.do" id="pagefrom_${actionclass}">
		<div style="margin: 0; padding: 1px 5px 5px;">
			<span>科目:</span>
			<select name="uid" class="form-control" data-toggle="selectpicker">
				<option value="">全部</option>
				<c:forEach items="${list }" var="item">
					<option value="${item.id }">${item.name }</option>
				</c:forEach>
			</select>

			<div class="btn-group">
				<button type="submit" class="btn-green" data-icon="search">统计</button>
			</div>
			<!--             <button type="button" class="btn-blue" data-toggle="dialog" data-options="{url:'../../html/datagrid/datagrid-search-source.html', id:'dialog-datagrid-search', width:1000, height:600, title:'查看Datagrid示例- 页头搜索、自定义编辑 - 源码'}">点击查看示例源码</button> -->
			<div class="btn-group"></div>
		</div>
	</form>
</div>
<div class="bjui-pageContent tableContent">
	<div id="container11" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
</div>
<c:if test="${not empty course }">
	<script type="text/javascript">
		$(function() {
			$('#container11').highcharts({
				chart : {
					type : 'column'
				},
				title : {
					text : '${course.name} - 各分数段的学生人数'
				},
				xAxis : {
					categories : [
						'60以下',
						'60-70及格',
						'70-90良',
						'90-100优'
					],
					crosshair : true
				},
				yAxis : {
					min : 0,
					title : {
						text : '人数 (人)'
					}
				},
				tooltip : {
					headerFormat : '<span style="font-size:10px">{point.key}</span><table>',
					pointFormat : '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
						'<td style="padding:0"><b>{point.y:.0f} 人</b></td></tr>',
					footerFormat : '</table>',
					shared : true,
					useHTML : true
				},
				plotOptions : {
					column : {
						pointPadding : 0.2,
						borderWidth : 0
					}
				},
				series : [ {
					name : '人数',
					data : [ ${count1},  ${count2},  ${count3},  ${count4} ]
				} ]
			});
		});
		
	</script>
</c:if>

WebRoot/jsp/listClazzStudent.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../common/head.jsp"%>
<div class="bjui-pageHeader">
	<form data-toggle="ajaxsearch" action="${ctx}/sys/query${actionclass}.do" id="pagefrom_${actionclass}">
		<div style="margin: 0; padding: 1px 5px 5px;">
			<span>:</span>
			<input type="text" name="s_" class="form-control" size="13">

<!-- 			<span>:</span> -->
<!-- 			 <select name="type"  class="form-control" data-toggle="selectpicker"> -->
<!--                 <option value="">全部</option> -->
<!--             </select>  -->

			<div class="btn-group">
				<button type="submit" class="btn-green" data-icon="search">搜索</button>
			</div>
			<!--             <button type="button" class="btn-blue" data-toggle="dialog" data-options="{url:'../../html/datagrid/datagrid-search-source.html', id:'dialog-datagrid-search', width:1000, height:600, title:'查看Datagrid示例- 页头搜索、自定义编辑 - 源码'}">点击查看示例源码</button> -->
			<div class="btn-group">
				<button type="button" class="btn-blue" data-url="${ctx}/sys/add2${actionclass}.do" data-toggle="navtab"
					data-options="{reloadWarn:''}" data-id="baseAdd" data-icon="plus" title="添加记录">添加${actionname}</button>
				&nbsp;
				<button type="button" class="btn-red" data-url="${ctx}/sys/delete${actionclass}.do" data-toggle="doajaxchecked"
					data-confirm-msg="确定要删除选中项吗？" data-idname="ids" data-group="ids" data-icon="remove" title="">批量删除</button>
				&nbsp;
			</div>
		</div>
	</form>
</div>
<div class="bjui-pageContent tableContent">
	<table class="table table-bordered" data-toggle="tablefixed" data-width="100%" data-nowrap="true">
		<thead>
			<tr>
				<th width="2%">
					<input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck">
				</th>
                <th>学号</th>
                <th>姓名</th>
                <th>专业</th>
                <th>班级</th>

                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        	<c:forEach items="${SESSION_PAGE.list}" var="item">
            <tr data-id="${item.id }">
            	<td>
					<input type="checkbox" name="ids" data-toggle="icheck" value="${item.id }">
				</td>
				<td>${item.student.uname}</td>
				<td>${item.student.userName}</td>
				<td>${item.student.zhuanye}</td>
				<td>${item.student.banji}</td>

                <td>
					<a href="${ctx}/sys/get${actionclass}.do?uid=${item.id}" class="btn btn-green" data-toggle="navtab"
						data-options="{reloadWarn:''}" data-id="baseAdd" data-reload-warn="本页已有打开的内容，确定将刷新本页内容，是否继续？"
						data-title="${actionname}信息">查看</a>
					<a href="${ctx}/sys/delete${actionclass}.do?ids=${item.id}" class="btn btn-red" data-toggle="doajax"
						data-confirm-msg="确定要删除该行信息吗？">删除</a>
				</td>
            </tr>
            </c:forEach>
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter">
	<div data-toggle="pagination"
		data-options="{total:${SESSION_PAGE.totalNumber}, pageCurrent:${SESSION_PAGE.currentPageNumber}, form:'#pagefrom_${actionclass}'}">
	</div>
</div>

WebRoot/jsp/listPaper.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../common/head.jsp"%>
<div class="bjui-pageHeader">
	<form data-toggle="ajaxsearch" action="${ctx}/sys/query${actionclass}.do" id="pagefrom_${actionclass}">
		<div style="margin: 0; padding: 1px 5px 5px;">
			<span>试卷编号:</span>
			<input type="text" name="s_sid" class="form-control" size="13">

<!-- 			<span>:</span> -->
<!-- 			 <select name="type"  class="form-control" data-toggle="selectpicker"> -->
<!--                 <option value="">全部</option> -->
<!--             </select>  -->

			<div class="btn-group">
				<button type="submit" class="btn-green" data-icon="search">搜索</button>
			</div>
			<!--             <button type="button" class="btn-blue" data-toggle="dialog" data-options="{url:'../../html/datagrid/datagrid-search-source.html', id:'dialog-datagrid-search', width:1000, height:600, title:'查看Datagrid示例- 页头搜索、自定义编辑 - 源码'}">点击查看示例源码</button> -->
			<div class="btn-group">
				<button type="button" class="btn-blue" data-url="${ctx}/sys/add2${actionclass}.do" data-toggle="navtab"
					data-options="{reloadWarn:''}" data-id="baseAdd" data-icon="plus" title="添加记录">自动组卷</button>
				&nbsp;
				<button type="button" class="btn-red" data-url="${ctx}/sys/delete${actionclass}.do" data-toggle="doajaxchecked"
					data-confirm-msg="确定要删除选中项吗？" data-idname="ids" data-group="ids" data-icon="remove" title="">批量删除</button>
				&nbsp;
			</div>
		</div>
	</form>
</div>
<div class="bjui-pageContent tableContent">
	<table class="table table-bordered" data-toggle="tablefixed" data-width="100%" data-nowrap="true">
		<thead>
			<tr>
				<th width="2%">
					<input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck">
				</th>
                <th>科目名称</th>
                <th>教师工号</th>
                <th>教师姓名</th>
                <th>试卷编号</th>
                <th>试卷名称</th>
                <th>考试时长</th>
                <th>有效</th>

                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        	<c:forEach items="${SESSION_PAGE.list}" var="item">
            <tr data-id="${item.id }">
            	<td>
					<input type="checkbox" name="ids" data-toggle="icheck" value="${item.id }">
				</td>
				<td>${item.course.name}</td>
				<td>${item.course.teacher.uname}</td>
				<td>${item.course.teacher.userName}</td>
				<td>${item.sid}</td>
				<td>${item.name}</td>
				<td>${item.examTime}</td>
				<td>${item.youxiao}</td>

                <td>
					<a href="${ctx}/sys/get${actionclass}.do?uid=${item.id}" class="btn btn-green" data-toggle="navtab"
						data-options="{reloadWarn:''}" data-id="baseAdd" data-reload-warn="本页已有打开的内容，确定将刷新本页内容，是否继续？"
						data-title="${actionname}信息">查看</a>
					<a href="${ctx}/sys/delete${actionclass}.do?ids=${item.id}" class="btn btn-red" data-toggle="doajax"
						data-confirm-msg="确定要删除该行信息吗？">删除</a>
				</td>
            </tr>
            </c:forEach>
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter">
	<div data-toggle="pagination"
		data-options="{total:${SESSION_PAGE.totalNumber}, pageCurrent:${SESSION_PAGE.currentPageNumber}, form:'#pagefrom_${actionclass}'}">
	</div>
</div>

WebRoot/jsp/main.jsp
<%@ page pageEncoding="UTF-8"%>
<%@ include file="../common/head.jsp"%>
<c:if test="${empty SESSION_BEAN }">
<script type="text/javascript" language="javascript">
	top.location.href='${pageContext.request.contextPath}/index.jsp';
</script>
</c:if>
<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>${appTitle }</title>
<%@ include file="../common/js.jsp"%>
</head>
<body>
    <!--[if lte IE 7]>
        <div id="errorie"><div>您还在使用老掉牙的IE，正常使用系统前请升级您的浏览器到 IE8以上版本 <a target="_blank" href="http://windows.microsoft.com/zh-cn/internet-explorer/ie-8-worldwide-languages">点击升级</a>&nbsp;&nbsp;强烈建议您更改换浏览器：<a href="http://down.tech.sina.com.cn/content/40975.html" target="_blank">谷歌 Chrome</a></div></div>
    <![endif]-->
    <div id="bjui-top" class="bjui-header">
        <div class="container_fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapsenavbar" data-target="#bjui-top-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <nav class="collapse navbar-collapse" id="bjui-top-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="datetime"><a><span id="bjui-date">0000/00/00</span> <span id="bjui-clock">00:00:00</span></a></li>
                    <li><a href="javascript:;">账号：${SESSION_BEAN.user.uname }</a></li>
                    <li><a href="javascript:;">角色：${SESSION_BEAN.user.role }</a></li>
                    <li><a href="${ctx}/com/update2Password.do" data-toggle="dialog" data-id="sys_user_changepass" data-mask="true" data-width="400" data-height="300">修改密码</a></li>
                    <li><a href="${ctx}/com/logout.do" style="font-weight:bold;">&nbsp;<i class="fa fa-power-off"></i> 注销登陆</a></li>
<!--                     <li class="dropdown"><a href="#" class="dropdown-toggle bjui-fonts-tit" data-toggle="dropdown" title="更改字号"><i class="fa fa-font"></i> 大</a> -->
<!--                         <ul class="dropdown-menu" role="menu" id="bjui-fonts"> -->
<!--                             <li><a href="javascript:;" class="bjui-font-a" data-toggle="fonts"><i class="fa fa-font"></i> 特大</a></li> -->
<!--                             <li><a href="javascript:;" class="bjui-font-b" data-toggle="fonts"><i class="fa fa-font"></i> 大</a></li> -->
<!--                             <li><a href="javascript:;" class="bjui-font-c" data-toggle="fonts"><i class="fa fa-font"></i> 中</a></li> -->
<!--                             <li><a href="javascript:;" class="bjui-font-d" data-toggle="fonts"><i class="fa fa-font"></i> 小</a></li> -->
<!--                         </ul> -->
<!--                     </li> -->
<!--                     <li class="dropdown active"><a href="#" class="dropdown-toggle theme" data-toggle="dropdown" title="切换皮肤"><i class="fa fa-tree"></i></a> -->
<!--                         <ul class="dropdown-menu" role="menu" id="bjui-themes"> -->
<!--                            
<!--                             <li><a href="javascript:;" class="theme_default" data-toggle="theme" data-theme="default">&nbsp;<i class="fa fa-tree"></i> 黑白分明&nbsp;&nbsp;</a></li> -->
<!--                             <li><a href="javascript:;" class="theme_orange" data-toggle="theme" data-theme="orange">&nbsp;<i class="fa fa-tree"></i> 橘子红了</a></li> -->
<!--                             --> -->
<!--                             <li><a href="javascript:;" class="theme_purple" data-toggle="theme" data-theme="purple">&nbsp;<i class="fa fa-tree"></i> 紫罗兰</a></li> -->
<!--                             <li class="active"><a href="javascript:;" class="theme_blue" data-toggle="theme" data-theme="blue">&nbsp;<i class="fa fa-tree"></i> 天空蓝</a></li> -->
<!--                             <li><a href="javascript:;" class="theme_green" data-toggle="theme" data-theme="green">&nbsp;<i class="fa fa-tree"></i> 绿草如茵</a></li> -->
<!--                         </ul> -->
<!--                     </li> -->
<!--                     <li><a href="javascript:;" onclick="bjui_index_exchange()" title="横向收缩/充满屏幕"><i class="fa fa-exchange"></i></a></li> -->
                </ul>
            </nav>
        </div>
    </div>
    <header class="navbar bjui-header" id="bjui-navbar">
        <div class="container_fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" id="bjui-navbar-collapsebtn" data-toggle="collapsenavbar" data-target="#bjui-navbar-collapse" aria-expanded="false">
                    <i class="fa fa-angle-double-right"></i>
                </button>
<%--                <a class="navbar-brand" href="${ctx}/exit.jsp"><img src="${ctx}/static/logo.png" height="30"></a>--%>
            </div>
            <nav class="collapse navbar-collapse" id="bjui-navbar-collapse">
                <ul class="nav navbar-nav navbar-right" id="bjui-hnav-navbar">
                    <li class="active">
                        <a href="${ctx}/com/menu.do" data-toggle="sidenav" data-id-key="targetid">系统菜单</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <div id="bjui-body-box">
        <div class="container_fluid" id="bjui-body">
            <div id="bjui-sidenav-col">
                <div id="bjui-sidenav">
                    <div id="bjui-sidenav-arrow" data-toggle="tooltip" data-placement="left" data-title="隐藏左侧菜单">
                        <i class="fa fa-long-arrow-left"></i>
                    </div>
                    <div id="bjui-sidenav-box">
                        
                    </div>
                </div>
            </div>
            <div id="bjui-navtab" class="tabsPage">
                <div id="bjui-sidenav-btn" data-toggle="tooltip" data-title="显示左侧菜单" data-placement="right">
                    <i class="fa fa-bars"></i>
                </div>
                <div class="tabsPageHeader">
                    <div class="tabsPageHeaderContent">
                        <ul class="navtab-tab nav nav-tabs">
                            <li><a href="javascript:;"><span><i class="fa fa-home"></i> #maintab#</span></a></li>
                        </ul>
                    </div>
                    <div class="tabsLeft"><i class="fa fa-angle-double-left"></i></div>
                    <div class="tabsRight"><i class="fa fa-angle-double-right"></i></div>
                    <div class="tabsMore"><i class="fa fa-angle-double-down"></i></div>
                </div>
                <ul class="tabsMoreList">
                    <li><a href="javascript:;">#maintab#</a></li>
                </ul>
                <div class="navtab-panel tabsPageContent">
                    <div class="navtabPage unitBox">
                        <div class="bjui-pageContent">
                                <pre class="" style="font-weight: bold;font-size: 16px;color:green">欢迎您: ${SESSION_BEAN.user.userName }
                                </pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="${ctx}/static/B-JUI/other/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

WebRoot/jsp/modifyCourse.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../common/head.jsp"%>
<div class="bjui-pageContent">
	<form action="${ctx}/sys/update${actionclass}.do" id="j_custom_form" data-toggle="ajaxform">
		<input type="hidden" value="${modifybean.id}" name="id" />
		<div class="bjui-row col-3">
			<label class="row-label">科目名称</label>
			<div class="row-input">
				<input type="text" name="name" id="Course_name" value="${modifybean.name}" data-rule="required">
			</div>
			<br />

			<label class="row-label">授课教师</label>
			<div class="row-input">
				<select name="teacherId" id="Course_teacher" data-rule="required">
					<c:forEach items="${list }" var="item">
						<option value="${item.id }">${item.fname }</option>
					</c:forEach>
				</select>
			</div>
			<br />



		</div>
	</form>
	<table class="table table-bordered" data-toggle="tablefixed" data-width="100%" data-nowrap="true">
		<thead>
			<tr>
				<th width="100">班级</th>
				<th width="100">学号</th>
				<th width="100">姓名</th>
				<th width="100">性别</th>
				<th width="100">联系电话</th>
				<th width="100">邮箱</th>
				<th width="100">出生日期</th>
				<th width="100">联系地址</th>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${stuList}" var="item">
				<tr data-id="${item.id }">
					<td>${item.clazz.name}</td>
					<td>${item.uname}</td>
					<td>${item.userName}</td>
					<td>${item.userGender}</td>
					<td>${item.userPhone}</td>
					<td>${item.userEmail}</td>
					<td>${item.userBirth}</td>
					<td>${item.userAddress}</td>
				</tr>
			</c:forEach>
		</tbody>
	</table>
</div>
<div class="bjui-pageFooter">
	<ul>
		<li>
			<button type="button" class="btn-close" data-icon="close">取消</button>
		</li>
		<li>
			<button type="submit" class="btn-default" data-icon="save">保存</button>
		</li>
	</ul>
</div>
<script type="text/javascript">
	$("#Course_teacher").val("${modifybean.teacher.id}");
</script>